In [1]:
import numpy as np

In [2]:
# create two square matrix
x = np.array([[1,5,6],[8,5,9],[1,0,3]])
z = np.array([[12,20,-3],[5,-8,5],[6,9,17]])
print(x,'\n')
print(z)

[[1 5 6]
 [8 5 9]
 [1 0 3]] 

[[12 20 -3]
 [ 5 -8  5]
 [ 6  9 17]]


In [3]:
# Add and sustract the matrices x and z
r_added = x.__add__(z)
r_sub = x.__sub__(z)
print(r_added,'\n')
print(r_sub)

[[13 25  3]
 [13 -3 14]
 [ 7  9 20]] 

[[-11 -15   9]
 [  3  13   4]
 [ -5  -9 -14]]


In [4]:
#pieceswise multiplication and multiplication of two matrices
r_piecewise = x.__mul__(z)
r_mul = x.__matmul__(z)
print(r_piecewise,'\n')
print(r_mul)

[[ 12 100 -18]
 [ 40 -40  45]
 [  6   0  51]] 

[[ 73  34 124]
 [175 201 154]
 [ 30  47  48]]


In [5]:
# 1x+1y=2 and 10x+35y=30
A = np.array([[1,1],[10,35]])
b = np.array([[2],[30]])

In [6]:
# Verify the size of matrix A and b
print('dim. of matrix A =',A.shape)
print('dim. of vector b =',b.shape)

dim. of matrix A = (2, 2)
dim. of vector b = (2, 1)


In [7]:
# Find the det(A)
np.linalg.det(A)

25.000000000000007

In [8]:
# Find the inverse of the matrix A
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 1.4  -0.04]
 [-0.4   0.04]]


In [9]:
# find the solution
sol = inv_A.dot(b)
print(sol)

[[1.6]
 [0.4]]


In [10]:
print(1*1.6 + 1*0.4)
print(10*1.6 + 35*0.4)

2.0
30.0
